# Generated by Django 2.2.10 on 2021-06-05 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=250)),
                ('attached_files', models.URLField()),
                ('sent_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('scheduled_date', models.TimeField(null=True)),
                ('updated', models.TimeField(auto_now=True)),
                ('status', models.CharField(choices=[('submitted', 'Non traité'), ('scheduled', 'programmé'), ('done', 'traité')], max_length=20)),
                ('decision', models.CharField(max_length=250)),
                ('remarks', models.CharField(max_length=250)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='owner', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-sent_date',),
            },
        ),
        migrations.CreateModel(
            name='Proces_verbal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('link_to', models.URLField()),
                ('date', models.DateTimeField()),
                ('closing_hour', models.TimeField()),
                ('status', models.CharField(max_length=100)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('validated_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('date', models.DateTimeField()),
                ('body', models.CharField(max_length=500)),
                ('attached_files', models.URLField()),
                ('created', models.TimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(max_length=50)),
                ('folders_to_treat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Dossier')),
                ('guests', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests_list', to=settings.AUTH_USER_MODEL)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='meeting_organizer', to=settings.AUTH_USER_MODEL)),
                ('pv', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Proces_verbal')),
            ],
        ),
    ]
