# Generated by Django 3.2.4 on 2021-07-01 12:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=50)),
                ('profile_pic', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('VSoutenance', 'Validation Soutenance'), ('Vstage', 'Validation stage')], max_length=50)),
                ('title', models.CharField(max_length=250)),
                ('attached_files', models.URLField(blank=True, null=True)),
                ('sent_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('scheduled_date', models.TimeField(blank=True, null=True)),
                ('updated', models.TimeField(auto_now=True)),
                ('status', models.CharField(choices=[('submitted', 'Non traité'), ('scheduled', 'programmé'), ('done', 'traité')], max_length=20)),
                ('decision', models.CharField(blank=True, max_length=250, null=True)),
                ('remarks', models.CharField(blank=True, max_length=250, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='owner', to='app.candidat')),
            ],
            options={
                'ordering': ('-sent_date',),
            },
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('value', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=50)),
                ('grade', models.CharField(max_length=50)),
                ('organization', models.CharField(max_length=50)),
                ('profile_pic', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Proces_verbal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_conseil', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('closing_hour', models.TimeField()),
                ('status', models.CharField(max_length=100)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('link_to', models.URLField()),
                ('folders_treated', models.ManyToManyField(to='app.Dossier')),
                ('members_absent', models.ManyToManyField(related_name='absent_list', to='app.Member')),
                ('members_present', models.ManyToManyField(related_name='presents_list', to='app.Member')),
                ('validated_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.member')),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('date', models.DateTimeField()),
                ('body', models.TextField()),
                ('attached_files', models.URLField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=50, verbose_name='submitted')),
                ('folders_to_treat', models.ManyToManyField(to='app.Dossier')),
                ('guests', models.ManyToManyField(to='app.Member')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='meeting_organizer', to='app.member')),
                ('pv', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='meeting_pv', to='app.proces_verbal')),
            ],
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('grade', models.CharField(max_length=50)),
                ('organization', models.CharField(max_length=50)),
                ('interests', models.ManyToManyField(to='app.Interest')),
            ],
        ),
        migrations.AddField(
            model_name='dossier',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='app.member'),
        ),
    ]
