# Generated by Django 3.2.4 on 2021-06-30 19:47

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=50)),
                ('profile_pic', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('grade', models.CharField(max_length=50)),
                ('organization', models.CharField(max_length=50)),
                ('interests', djongo.models.fields.ArrayField(model_container=app.models.Interest)),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('value', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Proces_verbal',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('link_to', models.URLField()),
                ('date', models.DateTimeField()),
                ('closing_hour', models.TimeField()),
                ('status', models.CharField(max_length=100)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('validated_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, default='', primary_key=True, serialize=False, verbose_name='')),
                ('title', models.CharField(max_length=250)),
                ('date', models.DateTimeField()),
                ('body', models.TextField()),
                ('attached_files', models.URLField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=50, verbose_name='submitted')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='meeting_organizer', to=settings.AUTH_USER_MODEL)),
                ('pv', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.proces_verbal')),
            ],
        ),
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=250)),
                ('attached_files', models.URLField(blank=True, null=True)),
                ('sent_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('scheduled_date', models.TimeField(blank=True, null=True)),
                ('updated', models.TimeField(auto_now=True)),
                ('status', models.CharField(choices=[('submitted', 'Non traité'), ('scheduled', 'programmé'), ('done', 'traité')], max_length=20)),
                ('decision', models.CharField(blank=True, max_length=250, null=True)),
                ('remarks', models.CharField(blank=True, max_length=250, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='owner', to='app.candidat')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-sent_date',),
            },
        ),
    ]
