# Generated by Django 2.2.10 on 2021-06-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210609_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='body',
            field=models.TextField(),
        ),
    ]
