# Generated by Django 3.2.4 on 2021-07-01 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210610_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=50)),
                ('profile_pic', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='_id',
        ),
        migrations.AddField(
            model_name='meeting',
            name='folders_to_treat',
            field=models.ManyToManyField(to='app.Dossier'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidat',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='owner', to='app.candidat'),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='type',
            field=models.CharField(choices=[('VSoutenance', 'Validation Soutenance'), ('Vstage', 'Validation stage')], max_length=50),
        ),
        migrations.AlterField(
            model_name='expert',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='expert',
            name='interests',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='pv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='meeting_pv', to='app.proces_verbal'),
        ),
        migrations.AlterField(
            model_name='proces_verbal',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='meeting',
            name='guests',
            field=models.ManyToManyField(to='app.Member'),
        ),
    ]
