# Generated by Django 3.2.4 on 2021-06-30 18:36

import app.models
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210610_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=50)),
                ('profile_pic', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('grade', models.CharField(max_length=50)),
                ('organization', models.CharField(max_length=50)),
                ('interests', djongo.models.fields.ArrayField(model_container=app.models.Interest)),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('value', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='folders_to_treat',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='guests',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='id',
        ),
        migrations.AddField(
            model_name='meeting',
            name='_id',
            field=djongo.models.fields.ObjectIdField(auto_created=True, default='', primary_key=True, serialize=False, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=models.CharField(max_length=50, verbose_name='submitted'),
        ),
        migrations.AlterField(
            model_name='proces_verbal',
            name='id',
            field=djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='owner', to='app.candidat'),
        ),
    ]
